"""Regression test: bilayer graphene density scan against saved SCF reference.

Requires contimod.  Skipped automatically when contimod is not installed.
Reference data generated by tests/generate_bilayer_reference.py.
"""
from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

import numpy as np
import pytest

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")
_CACHE_ROOT = Path(tempfile.gettempdir()) / "cpp_hf_optional_cache"
os.environ.setdefault("NUMBA_CACHE_DIR", str(_CACHE_ROOT / "numba"))
os.environ.setdefault("MPLCONFIGDIR", str(_CACHE_ROOT / "matplotlib"))

REPO_ROOT = Path(__file__).resolve().parents[1]
for optional_src in (
    REPO_ROOT.parent / "contimod" / "src",
    REPO_ROOT.parent / "contimod_graphene" / "src",
):
    if optional_src.exists() and str(optional_src) not in sys.path:
        sys.path.insert(0, str(optional_src))

contimod = pytest.importorskip("contimod")

import cpp_hf
from cpp_hf import SCFConfig, solve_scf
from cpp_hf.symmetry import make_project_fn

from contimod.meanfield.init_guess import init_to_density_matrix
from contimod.utils.spectrum_fermi import FermiParams
import contimod as cm

DATA_PATH = Path(__file__).parent / "data" / "bilayer_reference.npz"
PER_CM = 0.246e-7


def _flip_k(
    A: np.ndarray,
    k_convention: str,
    flip_axes: tuple[int, ...],
) -> np.ndarray:
    if k_convention == "flip":
        return np.flip(A, axis=flip_axes)
    if k_convention == "mod":
        nk1, nk2 = A.shape[0], A.shape[1]
        i = (
            (-np.arange(nk1, dtype=np.int32)) % nk1
            if 0 in flip_axes
            else np.arange(nk1, dtype=np.int32)
        )
        j = (
            (-np.arange(nk2, dtype=np.int32)) % nk2
            if 1 in flip_axes
            else np.arange(nk2, dtype=np.int32)
        )
        return A[i[:, None], j[None, :], ...]
    raise ValueError(f"k_convention must be 'mod' or 'flip', got {k_convention!r}")


def _make_time_reversal_U(s2: np.ndarray, v1: np.ndarray) -> np.ndarray:
    return np.asarray(v1) @ (1j * np.asarray(s2))


def _make_pm_group(
    identity: np.ndarray,
    s1: np.ndarray,
    s2: np.ndarray,
    s3: np.ndarray,
    v3: np.ndarray,
) -> np.ndarray:
    spin_elems = [identity, s1, s2, s3]
    valley_elems = [identity, v3]
    return np.stack([S @ V for S in spin_elems for V in valley_elems], axis=0)


def _make_svp_project_fn(
    *,
    s3: np.ndarray,
    v3: np.ndarray,
    n_orb: int,
    outlier_sv: tuple[int, int] = (+1, +1),
    k_convention: str = "flip",
    k_flip_axes: tuple[int, ...] = (0,),
):
    s3_np = np.asarray(s3)
    v3_np = np.asarray(v3)
    nb = s3_np.shape[0]
    n_blocks = nb // n_orb
    so, vo = float(outlier_sv[0]), float(outlier_sv[1])

    idx_outlier = None
    idx_same_v = None
    idx_other_v: list[int] = []

    for i in range(n_blocks):
        s_val = float(np.sign(np.real(s3_np[i * n_orb, i * n_orb])))
        v_val = float(np.sign(np.real(v3_np[i * n_orb, i * n_orb])))
        if s_val == so and v_val == vo:
            idx_outlier = i
        elif v_val == vo:
            idx_same_v = i
        else:
            idx_other_v.append(i)

    if idx_outlier is None or idx_same_v is None or len(idx_other_v) != 2:
        raise ValueError(
            "Could not identify 4 spin-valley blocks from s3/v3 "
            f"(n_orb={n_orb}, nb={nb}, outlier_sv={outlier_sv})"
        )

    def _sl(i: int) -> slice:
        return slice(i * n_orb, (i + 1) * n_orb)

    sl_same = _sl(idx_same_v)
    sl_ov0 = _sl(idx_other_v[0])
    sl_ov1 = _sl(idx_other_v[1])

    mask = np.zeros((nb, nb), dtype=np.float64)
    for i in range(n_blocks):
        a, b = i * n_orb, (i + 1) * n_orb
        mask[a:b, a:b] = 1.0

    k_conv = str(k_convention)
    k_axes = tuple(k_flip_axes)

    def project(P: np.ndarray) -> np.ndarray:
        P_arr = np.asarray(P)
        out = np.array(P_arr * mask, copy=True)

        P_same = P_arr[..., sl_same, sl_same]
        P_ov0_flip = _flip_k(P_arr[..., sl_ov0, sl_ov0], k_conv, k_axes)
        P_ov1_flip = _flip_k(P_arr[..., sl_ov1, sl_ov1], k_conv, k_axes)

        Q = (P_same + P_ov0_flip + P_ov1_flip) / 3.0
        Q_flip = _flip_k(Q, k_conv, k_axes)

        out[..., sl_same, sl_same] = Q
        out[..., sl_ov0, sl_ov0] = Q_flip
        out[..., sl_ov1, sl_ov1] = Q_flip
        return out

    return project


def _load_reference():
    """Load reference data, skip test if file missing."""
    if not DATA_PATH.exists():
        pytest.skip(f"Reference file not found: {DATA_PATH}")
    return np.load(str(DATA_PATH), allow_pickle=False)


def _build_bilayer_setup(ref):
    """Build contimod bilayer problem matching reference parameters."""
    nk = int(ref["nk"])
    kmax = float(ref["kmax"])
    U_meV = float(ref["U_meV"])
    temperature = float(ref["temperature"])
    epsilon_r = float(ref["epsilon_r"])
    d_gate = float(ref["d_gate"])
    init_scale = float(ref["init_scale"])

    model = cm.graphene.MultilayerAB(valleyful=True, spinful=True, U=U_meV)
    h_template = model.discretize(nk=nk, kmax=kmax)
    h_template.fermi = FermiParams(T=temperature, mu=0.0)

    ne_cn = float(h_template.state.compute_density_from_filling(0.5 - 1e-6))
    weights = np.asarray(h_template.kmesh.weights)

    Vq = cm.coulomb.dualgate_coulomb(
        h_template.kmesh.distance_grid, epsilon_r=epsilon_r, d_gate=d_gate,
    )
    Vq = np.asarray(Vq.magnitude)[..., None, None]

    identity_op = np.asarray(model.identity)
    s1, s2, s3 = [np.asarray(model.spin_op(i)) for i in (1, 2, 3)]
    v1, v3 = np.asarray(model.valley_op(1)), np.asarray(model.valley_op(3))
    U_tr = _make_time_reversal_U(s2, v1)

    projector_sv = 0.25 * (identity_op + s3) @ (identity_op + v3)
    sv_contrast = -projector_sv + 3.0 * (identity_op - projector_sv)

    seeds = {
        "PM": h_template.get_operator("zero"),
        "SVP": -init_scale * h_template.get_operator(sv_contrast),
    }

    G_pm = _make_pm_group(identity_op, s1, s2, s3, v3)
    project_fns = {
        "PM": make_project_fn(
            unitary_group=G_pm,
            time_reversal_U=np.asarray(U_tr),
            time_reversal_k_convention="flip",
        ),
        "SVP": _make_svp_project_fn(
            s3=np.asarray(s3), v3=np.asarray(v3), n_orb=4,
            outlier_sv=(+1, +1), k_convention="flip", k_flip_axes=(0,),
        ),
    }

    return h_template, ne_cn, weights, Vq, seeds, project_fns, temperature


@pytest.fixture(scope="module")
def bilayer_setup():
    ref = _load_reference()
    setup = _build_bilayer_setup(ref)
    return ref, setup


def _run_one_point(setup, branch, n_cm12):
    """Run SCF for one branch/density combination."""
    h_template, ne_cn, weights, Vq, seeds, project_fns, temperature = setup

    dd = n_cm12 * 1e12 * (PER_CM ** 2)
    h_run = h_template.copy()
    h_run.fermi = FermiParams(T=temperature, mu=0.0)
    h_run.compute_chemicalpotential(density=float(ne_cn + dd))
    n_e = float(h_run.state.compute_density() / float(h_run.degeneracy))

    P0 = init_to_density_matrix(
        h_run, seeds[branch], density=None, T=temperature, init_kind="auto",
    )

    kernel = cpp_hf.HartreeFockKernel(
        weights=weights, hamiltonian=np.asarray(h_template.hs),
        coulomb_q=Vq, T=temperature,
        include_hartree=False, include_exchange=True,
    )
    config = SCFConfig(
        max_iter=500, mixing=0.2,
        density_tol=1e-7, comm_tol=1e-6,
        project_fn=project_fns[branch],
    )
    return solve_scf(kernel, np.asarray(P0), n_e, config=config)


# Energy tolerance for regression: the reference was generated with the
# same solver, so results should be reproducible to float32 precision.
E_ATOL = 1e-4


@pytest.mark.parametrize("branch", ["PM", "SVP"])
@pytest.mark.parametrize("n_cm12", [-0.60, -0.42, -0.25, -0.12, -0.05, 0.05, 0.12, 0.25])
def test_scf_energy_matches_reference(bilayer_setup, branch, n_cm12):
    ref, setup = bilayer_setup
    key = f"{branch}_{n_cm12:+.2f}"

    E_ref = float(ref[f"{key}/energy"])
    converged_ref = bool(ref[f"{key}/converged"])
    if not converged_ref:
        pytest.skip(f"Reference point {key} did not converge")

    result = _run_one_point(setup, branch, n_cm12)

    np.testing.assert_allclose(
        float(result.energy), E_ref, atol=E_ATOL,
        err_msg=f"Energy mismatch for {key}",
    )
    if not result.converged:
        density_res = float(result.history["density_residual"][result.iterations - 1])
        comm_res = float(result.history["commutator_residual"][result.iterations - 1])
        assert density_res < 3e-7 and comm_res < 1e-6, (
            f"{key} did not converge tightly enough: {result.message}"
        )


# ---------------------------------------------------------------------------
# Direct minimization solver vs SCF reference
# ---------------------------------------------------------------------------

def _run_one_point_direct(setup, branch, n_cm12):
    """Run direct minimization solver for one branch/density combination."""
    h_template, ne_cn, weights, Vq, seeds, project_fns, temperature = setup

    dd = n_cm12 * 1e12 * (PER_CM ** 2)
    h_run = h_template.copy()
    h_run.fermi = FermiParams(T=temperature, mu=0.0)
    h_run.compute_chemicalpotential(density=float(ne_cn + dd))
    n_e = float(h_run.state.compute_density() / float(h_run.degeneracy))

    P0 = init_to_density_matrix(
        h_run, seeds[branch], density=None, T=temperature, init_kind="auto",
    )

    kernel = cpp_hf.HartreeFockKernel(
        weights=weights, hamiltonian=np.asarray(h_template.hs),
        coulomb_q=Vq, T=temperature,
        include_hartree=False, include_exchange=True,
    )
    config = cpp_hf.SolverConfig(
        max_iter=200, tol_E=1e-7,
        project_fn=project_fns[branch],
    )
    return cpp_hf.solve(kernel, np.asarray(P0), n_e, config=config)


# The direct solver reaches correct energies (matching SCF to ~1e-8)
# even when the gradient hasn't formally converged to tol.
# We test energy accuracy, not gradient convergence.
DIRECT_E_ATOL = 1e-4


@pytest.mark.parametrize("branch", ["PM", "SVP"])
@pytest.mark.parametrize("n_cm12", [-0.60, -0.42, -0.25, -0.12, -0.05, 0.05, 0.12, 0.25])
def test_direct_solver_energy_matches_reference(bilayer_setup, branch, n_cm12):
    ref, setup = bilayer_setup
    key = f"{branch}_{n_cm12:+.2f}"

    E_ref = float(ref[f"{key}/energy"])
    converged_ref = bool(ref[f"{key}/converged"])
    if not converged_ref:
        pytest.skip(f"Reference point {key} did not converge")

    result = _run_one_point_direct(setup, branch, n_cm12)

    np.testing.assert_allclose(
        float(result.energy), E_ref, atol=DIRECT_E_ATOL,
        err_msg=f"Direct solver energy mismatch for {key}",
    )
